version: "3.8"
volumes:
  postgres:

services:

  back:
    image: partypurse:v0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      -  SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/partypurse_db


  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=partypurse_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432



  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"
