spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://host.docker.internal:5432/PartyPurseDB
    username: postgres
    password: 123456

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    path: /api-docs


logging:
  level:
    org.springframework.security: trace