spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/PartyPurseDB
    username: postgres
    password: 123456

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    path: /api-docs


logging:
  level:
    org.springframework.security: trace


regexp: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&+=_-]).{8,}$
