spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PartyPurseDB
    username: postgres
    password: 123456

  jpa:
    generate-ddl: true
    show-sql: true



logging:
  level:
    org.springframework.security: trace